# Generated by Django 3.1.5 on 2021-01-07 17:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
                ('description', models.TextField(default=' ')),
                ('price', models.CharField(default='0', max_length=100)),
                ('loaction', models.CharField(default=' ', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=15, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('crated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('password', models.CharField(max_length=100)),
                ('add', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.add')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
