# Generated by Django 3.1.5 on 2021-01-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='add',
        ),
        migrations.AddField(
            model_name='add',
            name='customuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.customuser'),
            preserve_default=False,
        ),
    ]
